platform :ios, '8.0'

target 'MonarchRouterExample' do
  use_frameworks!

  # Diffs for collections
  # https://github.com/tonyarnold/Differ
  pod 'Differ', '~> 1.4'

end


target 'MonarchRouter' do
    use_frameworks!
end
